project:
  type: website
  execute-dir: project
  output-dir: docs
  render: 
    - index.qmd
    - 1_foundations/foundations_njl.qmd
    - 2_functional_programming/functional-programming_njl.qmd
    - 5_techniques/techniques_njl.qmd
    - _products

execute:
  freeze: auto

website:
  title: "NCEAS Data Skills Group - Advanced R"
  repo-url: https://github.com/NCEAS-Data-Skills/advancedR
  repo-actions: [issue]
  sidebar: 
    title: "Notes"
    style: "docked"
    background: light
    border: true
    alignment: left
    collapse-level: 2
    contents:
    - section: "Foundations"
      contents: 
        - text: "Lyon Notes"
          href: 1_foundations/foundations_njl.qmd
    - section: "Functional Programming"
      contents: 
        - text: "Lyon Notes"
          href: 2_functional_programming/functional-programming_njl.qmd
    - section: "Techniques"
      contents: 
        - text: "Lyon Notes"
          href: 5_techniques/techniques_njl.qmd
  navbar:
    background: primary
    right:
      - text: "Highlights"
        menu: 
          - text: "Lyon Highlights"
            href: _products/highlights_njl.qmd
      - text: "People"
        menu: 
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
      - icon: github
        href: https://github.com/NCEAS-Data-Skills/advancedR
  page-footer:
    center: "Copyright 2024, NCEAS"
    background: secondary

format:
  html:
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
