---
title: "Welcome!"
format: html
---

This website stores the notes (and exercise answers) for the group of NCEAS employees working through Hadley Wickham's _Advanced R_ ebook. See below for the key links, a brief description of the sub-folders in the GitHub repository, and our meeting dates with associated topics.

## Key Links

Online ebook: [adv-r.hadley.nz](https://adv-r.hadley.nz/index.html)  
Solutions: [advanced-r-solutions.rbind.io](https://advanced-r-solutions.rbind.io/)  
Notes GitHub repo: [github.com/NCEAS-Data-Skills/advancedR](https://github.com/NCEAS-Data-Skills/advancedR)

## GitHub Repository Sub-folder Explanations

- `_products/` -- Potential products from this group to share with the broader NCEAS community
- `foundations/` -- Notes and exercises for chapters 2-8
- `meeting_notes/` -- Notes taken during meetings

## Meeting Schedule & Topics

Meetings are weekly on Thursdays at 12:30pm, online and in person in the Manzanita Room (when available). 

| Date       | Materials & Prep          |
|:-----------|:-------------------------:|
| 2024-07-25 | First meeting - look at foundations quizzes |
| 2024-08-15 | Read Ch. 2-4 & attempt exercises |
| 2024-08-22 | Read Ch. 5 & 6 & attempt exercises |
